Update rules.sqf due to recent changes
ArmaAchilles/ZGM_Achilles_Collection pull request #20
Opened 2020-04-19 11:13 UTC by TheRadiumDude

Update the `rules.sqf` file to have more clarity with certain rules, and to reflect recent changes in the team.

2020-04-20 08:55 UTC, CreepPork commented
I'll look into merging it soon.

2020-04-27 15:39 UTC, CreepPork requested changes

2020-04-27 15:39 UTC, CreepPork commented on src/ZGM-17_Achilles_Blufor.Altis/scripts/rules.sqf
> +<br/><font size='15'><font color='#ffa500'>Listen to Zeus. Do not tell Zeus what to do, instead provide suggestions. Abide by what Zeus asks you to do or wear and do not excessively beg Zeus to give
```suggestion
<br/><font size='15'><font color='#ffa500'>Listen to Zeus. Do not tell Zeus what to do, instead provide suggestions. Abide by what Zeus asks you to do or wear and do not excessively beg Zeus to give you armored or aerial vehicles. However, players are allowed to politely provide suggestions for a mission, and Zeus must respect that as well. If the Zeus is making an unsatisfactory experience, or the mission is nonsensical, this rule automatically doesn't apply.</font color></font size>
```

2020-04-27 19:24 UTC, TheRadiumDude commented on src/ZGM-17_Achilles_Blufor.Altis/scripts/rules.sqf
> +<br/><font size='15'><font color='#ffa500'>Listen to Zeus. Do not tell Zeus what to do, instead provide suggestions. Abide by what Zeus asks you to do or wear and do not excessively beg Zeus to give
Oops 😄

2020-05-13 15:24 UTC, merged